name: Koff GitHub Actions
on:
  push:
    branches: [master]
  pull_request:
    branches: [master, develop]
jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v4
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build
      - name: run eslint
        run: npm run lint
      - name: Job status
        run: echo "This job's status is ${{ job.status }}."
